//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel_Management_App.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwEmployee
    {
        public string Employee_Name { get; set; }
        public System.DateTime Date_Of_Birth { get; set; }
        public string Email { get; set; }
        public string Position { get; set; }
        public string Salary { get; set; }
        public string Citizenship { get; set; }
        public string FloorNumber { get; set; }
        public string Sex { get; set; }
        public int EmployeeID { get; set; }
        public int UserDataID { get; set; }
    }
}
